In [14]:
import pandas as pd
df = pd.read_csv("clean_data.csv")

def convertToFact(row):
    return f'restaurant("{row["name"]}","{row["cuisines"]}","{row["rest_type"]}",\
{row["rate"]},{row["dollar_sign"]},{row["restaurant_value"]},{row["x"]},{row["y"]}).\n'

df["asFact"] = df.apply(convertToFact, axis=1)

In [15]:
df = df[df['name'].str.len()<40]

In [17]:
df.shape

(3211, 9)

In [16]:
with open('knowledgeBase.pl', mode="w") as file:
    file.writelines(df.asFact.tolist())

In [26]:
df[(df.cuisines=='SouthIndian')&(df.rest_type=='QuickBites')&(df.dollar_sign==1)]\
.sort_values('restaurant_value',ascending=False)

,name,cuisines,rest_type,rate,dollar_sign,restaurant_value,x,y,asFact
262,Vidyarthi Bhavan,SouthIndian,QuickBites,4.4,1,5,-1.003758,-1.167589,"restaurant(""Vidyarthi Bhavan"",""SouthIndian"",""Q..."
699,Mavalli Tiffin Room (MTR),SouthIndian,QuickBites,4.0,1,5,0.307798,-1.485405,"restaurant(""Mavalli Tiffin Room (MTR)"",""SouthI..."
700,Brahmin's Coffee Bar,SouthIndian,QuickBites,4.8,1,5,0.245989,0.877737,"restaurant(""Brahmin's Coffee Bar"",""SouthIndian..."
2761,Veena Stores,SouthIndian,QuickBites,4.5,1,5,0.487653,0.520245,"restaurant(""Veena Stores"",""SouthIndian"",""Quick..."
2688,CTR,SouthIndian,QuickBites,4.7,1,5,0.966892,1.386820,"restaurant(""CTR"",""SouthIndian"",""QuickBites"",4...."
...,...,...,...,...,...,...,...,...,...
2393,Kaapi Kuteera,SouthIndian,QuickBites,3.0,1,0,0.321161,0.727427,"restaurant(""Kaapi Kuteera"",""SouthIndian"",""Quic..."
2402,Aditya Uphar,SouthIndian,QuickBites,3.0,1,0,-0.750766,1.487439,"restaurant(""Aditya Uphar"",""SouthIndian"",""Quick..."
647,New Udupi Upahar,SouthIndian,QuickBites,3.0,1,0,1.039915,1.051446,"restaurant(""New Udupi Upahar"",""SouthIndian"",""Q..."
2404,Hotel Coorg Style,SouthIndian,QuickBites,3.1,1,0,0.124896,0.192056,"restaurant(""Hotel Coorg Style"",""SouthIndian"",""..."
2506,Samprith Gowdru Mudde Hotel,SouthIndian,QuickBites,3.0,1,0,-0.469752,-1.718597,"restaurant(""Samprith Gowdru Mudde Hotel"",""Sout..."

In [28]:
df.x.min()

-4.4322519680715535